version: "3"
services:
  server:
    container_name: server
    build: .f
    ports: ['7654:5000']
    volumes: ['.:/app']
    depends_on:
      - db
    networks:
      - le_network
  db:
    container_name: db
    image: postgres
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - le_network
networks:
  le_network:
