"""dentist table

Revision ID: 4f9b456c2e8d
Revises: 
Create Date: 2023-08-23 19:11:42.170836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9b456c2e8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dentists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initials', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initials', 'last_name')
    )
    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentists_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentists_initials'), ['initials'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentists_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentists_last_name'))
        batch_op.drop_index(batch_op.f('ix_dentists_initials'))
        batch_op.drop_index(batch_op.f('ix_dentists_first_name'))

    op.drop_table('dentists')
    # ### end Alembic commands ###
